# Generated by Django 5.2.8 on 2025-11-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_name', models.CharField(max_length=200, verbose_name='선박명')),
                ('imo_number', models.CharField(max_length=20, unique=True, verbose_name='IMO 번호')),
                ('ship_type', models.CharField(blank=True, max_length=100, verbose_name='선박 종류')),
                ('gross_tonnage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='총톤수')),
                ('year_built', models.IntegerField(blank=True, null=True, verbose_name='건조년도')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '선박',
                'verbose_name_plural': '선박',
                'db_table': 'ships',
                'ordering': ['-created_at'],
            },
        ),
    ]
