# Generated by Django 5.2.8 on 2025-11-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declaration_type', models.CharField(choices=[('MD', 'Material Declaration'), ('SDoC', 'Supplier Declaration of Conformity')], max_length=10, verbose_name='신고서 유형')),
                ('item_name', models.CharField(max_length=200, verbose_name='품목명')),
                ('manufacturer', models.CharField(blank=True, max_length=200, verbose_name='제조사')),
                ('model_number', models.CharField(blank=True, max_length=100, verbose_name='모델번호')),
                ('hazardous_materials_json', models.JSONField(blank=True, null=True, verbose_name='유해물질 정보 (JSON)')),
                ('compliance_status', models.CharField(choices=[('compliant', '규정 준수'), ('non_compliant', '규정 미준수')], max_length=20, verbose_name='적합성 상태')),
                ('certification_number', models.CharField(blank=True, max_length=100, verbose_name='인증번호')),
                ('supplier_signature', models.CharField(max_length=200, verbose_name='전자서명')),
                ('supplier_name', models.CharField(max_length=100, verbose_name='서명자명')),
                ('signature_date', models.DateField(verbose_name='서명일')),
                ('submitted_date', models.DateTimeField(blank=True, null=True, verbose_name='제출일')),
                ('approved_date', models.DateTimeField(blank=True, null=True, verbose_name='승인일')),
                ('status', models.CharField(choices=[('draft', '초안'), ('submitted', '제출됨'), ('approved', '승인됨'), ('rejected', '거절됨')], default='draft', max_length=20, verbose_name='상태')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='거절 사유')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '신고서',
                'verbose_name_plural': '신고서',
                'db_table': 'declarations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeclarationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(auto_now_add=True, verbose_name='요청일')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='마감일')),
                ('status', models.CharField(choices=[('pending', '대기'), ('submitted', '제출됨'), ('approved', '승인됨'), ('rejected', '거절됨')], default='pending', max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '신고서 요청',
                'verbose_name_plural': '신고서 요청',
                'db_table': 'declaration_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HazardousMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=200, verbose_name='물질명')),
                ('cas_number', models.CharField(blank=True, max_length=50, verbose_name='CAS 번호')),
                ('content_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='함유율 (%)')),
                ('location_in_product', models.CharField(blank=True, max_length=200, verbose_name='제품 내 위치')),
                ('remarks', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '유해물질',
                'verbose_name_plural': '유해물질',
                'db_table': 'hazardous_materials',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100, unique=True, verbose_name='주문번호')),
                ('item_name', models.CharField(max_length=200, verbose_name='품목명')),
                ('item_description', models.TextField(blank=True, verbose_name='품목 설명')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='수량')),
                ('unit', models.CharField(max_length=50, verbose_name='단위')),
                ('order_date', models.DateField(verbose_name='주문일')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='납품일')),
                ('status', models.CharField(choices=[('pending', '대기'), ('requested', '요청됨'), ('completed', '완료')], default='pending', max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '구매 주문',
                'verbose_name_plural': '구매 주문',
                'db_table': 'purchase_orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
