# Generated by Django 5.2.8 on 2025-11-11 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('declarations', '0001_initial'),
        ('ships', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_declarations', to=settings.AUTH_USER_MODEL, verbose_name='승인자'),
        ),
        migrations.AddField(
            model_name='declaration',
            name='ship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to='ships.ship', verbose_name='선박'),
        ),
        migrations.AddField(
            model_name='declaration',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to='users.supplier', verbose_name='공급업체'),
        ),
        migrations.AddField(
            model_name='declarationrequest',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_declaration_requests', to=settings.AUTH_USER_MODEL, verbose_name='생성자'),
        ),
        migrations.AddField(
            model_name='declarationrequest',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declaration_requests', to='users.supplier', verbose_name='공급업체'),
        ),
        migrations.AddField(
            model_name='declaration',
            name='declaration_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='declaration', to='declarations.declarationrequest', verbose_name='신고서 요청'),
        ),
        migrations.AddField(
            model_name='hazardousmaterial',
            name='declaration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hazardous_materials', to='declarations.declaration', verbose_name='신고서'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL, verbose_name='생성자'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='ship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='ships.ship', verbose_name='선박'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='users.supplier', verbose_name='공급업체'),
        ),
        migrations.AddField(
            model_name='declarationrequest',
            name='purchase_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='declaration_request', to='declarations.purchaseorder', verbose_name='구매 주문'),
        ),
    ]
