# Generated by Django 5.2.8 on 2025-11-12 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declarations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='제목'),
        ),
    ]
