# Generated by Django 5.2.8 on 2025-11-12 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declarations', '0003_purchaseorder_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='item_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='품목명'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='수량'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='title',
            field=models.CharField(max_length=200, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='unit',
            field=models.CharField(blank=True, max_length=50, verbose_name='단위'),
        ),
    ]
