# Generated by Django 5.2.8 on 2025-11-12 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declarations', '0004_alter_purchaseorder_item_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='supplier',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='description',
            field=models.TextField(blank=True, verbose_name='설명'),
        ),
    ]
