# Generated by Django 5.2.8 on 2025-11-12 04:38

from django.db import migrations, models
from datetime import datetime
import random


def generate_declaration_numbers(apps, schema_editor):
    """Existing declarations에 declaration_number 생성"""
    Declaration = apps.get_model('declarations', 'Declaration')
    for idx, declaration in enumerate(Declaration.objects.all(), start=1):
        date_str = datetime.now().strftime('%Y%m%d')
        random_num = str(random.randint(1000, 9999))
        declaration.declaration_number = f'DEC-{date_str}-{random_num}-{idx}'
        declaration.save()


class Migration(migrations.Migration):

    dependencies = [
        ('declarations', '0005_remove_purchaseorder_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='declaration_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='신고서 번호'),
        ),
        migrations.AddField(
            model_name='declaration',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='제목'),
        ),
        migrations.RunPython(generate_declaration_numbers),
        migrations.AlterField(
            model_name='declaration',
            name='declaration_number',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='신고서 번호'),
        ),
    ]
