# Generated by Django 5.2.8 on 2025-11-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declarations', '0006_declaration_declaration_number_declaration_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='compliance_status',
            field=models.CharField(blank=True, choices=[('compliant', '규정 준수'), ('non_compliant', '규정 미준수')], max_length=20, verbose_name='적합성 상태'),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='declaration_type',
            field=models.CharField(blank=True, choices=[('MD', 'Material Declaration'), ('SDoC', 'Supplier Declaration of Conformity')], max_length=10, verbose_name='신고서 유형'),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='item_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='품목명'),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='signature_date',
            field=models.DateField(blank=True, null=True, verbose_name='서명일'),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='서명자명'),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='supplier_signature',
            field=models.CharField(blank=True, max_length=200, verbose_name='전자서명'),
        ),
    ]
