# Generated by Django 5.2.8 on 2025-11-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declarations', '0007_alter_declaration_compliance_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hazardousmaterial',
            name='content_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='함유율 (%)'),
        ),
        migrations.AlterField(
            model_name='hazardousmaterial',
            name='material_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='물질명'),
        ),
    ]
